// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzMo1vB4D1W2fieHLJAOxZwNKKc_iNuYY',
    appId: '1:519022808097:web:10e3309f003d45e880a760',
    messagingSenderId: '519022808097',
    projectId: 'diario-notaspro',
    authDomain: 'diario-notaspro.firebaseapp.com',
    storageBucket: 'diario-notaspro.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDt4LRfy8j1n5U7W1zKqVmqQrubUI6AHGI',
    appId: '1:519022808097:android:b9ea180ccd14565e80a760',
    messagingSenderId: '519022808097',
    projectId: 'diario-notaspro',
    storageBucket: 'diario-notaspro.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzMo1vB4D1W2fieHLJAOxZwNKKc_iNuYY',
    appId: '1:519022808097:web:60432e6e6b1964b480a760',
    messagingSenderId: '519022808097',
    projectId: 'diario-notaspro',
    authDomain: 'diario-notaspro.firebaseapp.com',
    storageBucket: 'diario-notaspro.firebasestorage.app',
  );
}
